# Generated by Django 5.0.9 on 2024-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptName', models.CharField(max_length=100)),
                ('DeptID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
