# Generated by Django 5.0.9 on 2024-09-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.department'),
            preserve_default=False,
        ),
    ]
